spring:
  config:
    import: file:.env[.properties]
  application:
    name: TCPManager
  jpa:
    hibernate.ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  flyway:
    enabled: true
springdoc:
  swagger-ui:
    path: /api/docs
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem